// Professional Email Dispatch Service for CareerSetu AI MFA & Password Reset
// Sends the pre-generated OTP via the backend SMTP/Resend transport (server function).
// The OTP is ALWAYS generated by rbac.ts (server-side) and passed here for delivery only.

import { dispatchResendOtpDirectServerFn } from "./auth.functions";

export interface EmailDispatchOptions {
  to: string;
  subject?: string;
  templateType: "STUDENT_LOGIN_MFA" | "STUDENT_SIGNUP_VERIFY" | "ADMIN_LOGIN_MFA" | "ADMIN_PASSWORD_RESET" | "ADMIN_FIRST_SETUP";
  recipientName?: string;
  otpCode?: string;
  expiresInMinutes?: number;
}

export interface EmailDispatchResult {
  success: boolean;
  message: string;
  isDevelopmentMode: boolean;
  maskedRecipient: string;
  challengeToken?: string;
  deliveryTimestamp: string;
  error?: string;
  /** Only present when Resend is not configured (local dev console log mode). */
  devOtp?: string;
}

// Mask Email helper
export function maskEmailAddress(email: string): string {
  if (!email || !email.includes("@")) return "******@domain.com";
  const [user, domain] = email.split("@");
  if (!user || !domain) return "******@domain.com";
  if (user.length <= 2) return `${user[0]}*@${domain}`;
  const first = user[0];
  const last = user[user.length - 1];
  const stars = "*".repeat(Math.max(3, user.length - 2));
  return `${first}${stars}${last}@${domain}`;
}

// Map templateType to sendEmailViaSmtp purpose
function mapToPurpose(
  templateType: EmailDispatchOptions["templateType"]
): "STUDENT_LOGIN" | "STUDENT_VERIFY" | "ADMIN_LOGIN" | "ADMIN_FIRST_SETUP" | "ADMIN_RESET" {
  if (templateType === "STUDENT_SIGNUP_VERIFY") return "STUDENT_VERIFY";
  if (templateType === "ADMIN_LOGIN_MFA") return "ADMIN_LOGIN";
  if (templateType === "ADMIN_FIRST_SETUP") return "ADMIN_FIRST_SETUP";
  if (templateType === "ADMIN_PASSWORD_RESET") return "ADMIN_RESET";
  return "STUDENT_LOGIN";
}

/**
 * Sends the pre-generated OTP code to the user's email via the backend server function.
 * The OTP is always sourced from rbac.ts (already hashed/stored). This function only handles delivery.
 */
export async function sendAuthenticationEmail(options: EmailDispatchOptions): Promise<EmailDispatchResult> {
  const { to, recipientName = "User", templateType, otpCode, expiresInMinutes = 10 } = options;
  const timestamp = new Date().toISOString();
  const masked = maskEmailAddress(to);
  const purpose = mapToPurpose(templateType);

  // If no OTP was passed (shouldn't happen in normal flow), log error and fail gracefully
  if (!otpCode) {
    console.error("[EMAIL-SERVICE] sendAuthenticationEmail called without otpCode — cannot dispatch.");
    return {
      success: false,
      message: "Internal error: OTP code was not provided for email dispatch.",
      isDevelopmentMode: false,
      maskedRecipient: masked,
      deliveryTimestamp: timestamp,
      error: "Missing otpCode",
    };
  }

  try {
    const res = await dispatchResendOtpDirectServerFn({
      data: {
        to,
        otpCode,
        purpose,
        recipientName,
        expiresInMinutes,
      },
    });

    if (res.success) {
      return {
        success: true,
        message: `Security code sent to ${masked}`,
        isDevelopmentMode: !res.sentViaSmtp,
        maskedRecipient: masked,
        deliveryTimestamp: timestamp,
        // In dev mode (no Resend configured), surface OTP so dev can test
        devOtp: res.sentViaSmtp ? undefined : otpCode,
      };
    }

    return {
      success: false,
      message: res.error || "Failed to dispatch verification code.",
      isDevelopmentMode: false,
      maskedRecipient: masked,
      deliveryTimestamp: timestamp,
      error: res.error,
    };
  } catch (err: any) {
    console.error("[EMAIL-SERVICE] dispatchResendOtpDirectServerFn failed:", err?.message || err);
    return {
      success: false,
      message: err?.message || "An unexpected error occurred dispatching verification email.",
      isDevelopmentMode: false,
      maskedRecipient: masked,
      deliveryTimestamp: timestamp,
      error: err?.message,
    };
  }
}
