// Supabase Edge Function: send-mfa-email
// Dispatches 6-digit security verification OTP emails via Resend API.
// OTP is generated by the caller (rbac.ts) and passed in the request body.
// RESEND_API_KEY is stored as a Supabase secret — never exposed to the client.
//
// Deploy:
//   supabase functions deploy send-mfa-email --project-ref vpihjwmimenuuauclalt --no-verify-jwt
//
// Set secret:
//   supabase secrets set RESEND_API_KEY=<your_key> --project-ref vpihjwmimenuuauclalt

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY") || "";
const FROM_EMAIL =
  Deno.env.get("RESEND_FROM_EMAIL") || "CareerSetu AI <onboarding@resend.dev>";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

function buildEmailHtml(params: {
  recipientName: string;
  otpCode: string;
  purpose: string;
  expiresInMinutes: number;
}): { subject: string; html: string; text: string } {
  const { recipientName, otpCode, purpose, expiresInMinutes } = params;

  const isAdmin =
    purpose === "ADMIN_LOGIN" ||
    purpose === "ADMIN_FIRST_SETUP" ||
    purpose === "ADMIN_RESET";

  const headerColor = isAdmin
    ? "#f59e0b"
    : purpose === "STUDENT_VERIFY"
    ? "#059669"
    : "#0284c7";

  const title = isAdmin
    ? purpose === "ADMIN_RESET"
      ? "Administrator Password Reset"
      : purpose === "ADMIN_FIRST_SETUP"
      ? "Initial Administrator Setup"
      : "Administrator Two-Factor Authentication"
    : purpose === "STUDENT_VERIFY"
    ? "Verify Your Student Account"
    : "Student Sign-In Verification";

  const greeting = isAdmin
    ? `Administrator,`
    : `Hello ${recipientName},`;

  const instruction = isAdmin
    ? "Use the following one-time code to complete your administrator authentication:"
    : "Use the following 6-digit code to verify your email and access your dashboard:";

  const subject = `CareerSetu: ${otpCode} is your verification code`;

  const text = `${title} — CareerSetu AI\n\n${greeting}\n\n${instruction}\n\nCode: ${otpCode}\n\nExpires in ${expiresInMinutes} minutes. Do not share this code.\n\nCareerSetu AI Security Team`;

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
</head>
<body style="margin:0;padding:0;background-color:#0f172a;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#f8fafc;">
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background-color:#0f172a;padding:40px 16px;">
    <tr>
      <td align="center">
        <table role="presentation" width="100%" style="max-width:540px;background-color:#1e293b;border-radius:24px;border:1px solid #334155;overflow:hidden;box-shadow:0 25px 50px -12px rgba(0,0,0,0.5);">
          <!-- Header -->
          <tr>
            <td style="padding:28px 32px 20px 32px;background:linear-gradient(135deg,#0f172a 0%,#1e1b4b 100%);border-bottom:1px solid #334155;">
              <table width="100%" cellspacing="0" cellpadding="0">
                <tr>
                  <td>
                    <div style="font-size:22px;font-weight:800;letter-spacing:-0.5px;color:#ffffff;">
                      Career<span style="color:#38bdf8;">Setu</span>
                      <span style="font-size:12px;padding:3px 8px;background:rgba(56,189,248,0.15);color:#38bdf8;border-radius:8px;border:1px solid rgba(56,189,248,0.3);font-weight:600;margin-left:6px;">AI</span>
                    </div>
                  </td>
                  <td align="right">
                    <span style="display:inline-block;padding:4px 12px;background:rgba(255,255,255,0.08);border-radius:999px;font-size:11px;font-weight:600;color:#94a3b8;letter-spacing:0.5px;text-transform:uppercase;">
                      Account Security
                    </span>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <!-- Body -->
          <tr>
            <td style="padding:32px;">
              <h1 style="margin:0 0 12px 0;font-size:20px;font-weight:700;color:#f8fafc;letter-spacing:-0.3px;">${title}</h1>
              <p style="margin:0 0 8px 0;font-size:14px;line-height:1.6;color:#cbd5e1;">${greeting}</p>
              <p style="margin:0 0 24px 0;font-size:14px;line-height:1.6;color:#94a3b8;">${instruction}</p>

              <!-- OTP Card -->
              <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin:24px 0;">
                <tr>
                  <td align="center" style="background:#090d16;border:1px dashed ${headerColor};border-radius:18px;padding:24px 16px;">
                    <div style="font-size:11px;letter-spacing:1.5px;text-transform:uppercase;color:#94a3b8;font-weight:600;margin-bottom:8px;">
                      Single-Use Security Code
                    </div>
                    <div style="font-family:'Courier New',Courier,monospace;font-size:42px;font-weight:800;letter-spacing:12px;color:#ffffff;text-shadow:0 0 16px ${headerColor};">
                      ${otpCode}
                    </div>
                    <div style="font-size:12px;color:#94a3b8;margin-top:10px;">
                      ⏱️ Valid for <strong style="color:#f8fafc;">${expiresInMinutes} minutes</strong>
                    </div>
                  </td>
                </tr>
              </table>

              <!-- Security notice -->
              <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:rgba(255,255,255,0.03);border-radius:14px;padding:16px;border:1px solid rgba(255,255,255,0.06);">
                <tr>
                  <td style="font-size:12px;line-height:1.6;color:#94a3b8;">
                    🔒 <strong style="color:#e2e8f0;">Security Notice:</strong> Never share this code with anyone. CareerSetu support will never ask for your verification code. If you did not initiate this, please ignore this email.
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="padding:20px 32px;background:#090d16;border-top:1px solid #1e293b;text-align:center;">
              <p style="margin:0;font-size:11px;color:#64748b;line-height:1.6;">
                This automated message was sent by CareerSetu AI Security System.<br>
                © ${new Date().getFullYear()} CareerSetu AI • All rights reserved.
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `.trim();

  return { subject, html, text };
}

serve(async (req: Request) => {
  // CORS preflight
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const body = await req.json();
    const {
      to,
      otpCode,
      purpose = "STUDENT_LOGIN",
      recipientName = "Student",
      expiresInMinutes = 10,
    } = body;

    if (!to || !otpCode) {
      return new Response(
        JSON.stringify({ error: "Missing required fields: 'to' and 'otpCode'" }),
        {
          status: 400,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }

    const { subject, html, text } = buildEmailHtml({
      recipientName,
      otpCode,
      purpose,
      expiresInMinutes,
    });

    // Dev fallback: if no Resend key configured, log to edge function console only.
    // The OTP is NOT returned in the response body for security.
    if (!RESEND_API_KEY || RESEND_API_KEY.trim().length === 0) {
      console.log(
        `[send-mfa-email] DEV FALLBACK — No RESEND_API_KEY set.\n` +
          `  To: ${to}\n  Purpose: ${purpose}\n  OTP logged server-side only (not returned to client).`
      );
      return new Response(
        JSON.stringify({
          success: true,
          mode: "dev_log",
          message:
            "No RESEND_API_KEY set. Email not sent. Set secret via: supabase secrets set RESEND_API_KEY=<key>",
        }),
        {
          status: 200,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }

    // Send via Resend API
    const resendRes = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${RESEND_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: FROM_EMAIL,
        to: [to],
        subject,
        html,
        text,
      }),
    });

    const resData = await resendRes.json();

    if (!resendRes.ok) {
      console.error("[send-mfa-email] Resend API error:", resData);
      return new Response(
        JSON.stringify({
          error: resData.message || "Failed to send email via Resend.",
          resend_error: resData,
        }),
        {
          status: 502,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }

    console.log(
      `[send-mfa-email] ✓ Delivered to ${to} | Resend ID: ${resData.id}`
    );

    return new Response(
      JSON.stringify({ success: true, messageId: resData.id }),
      {
        status: 200,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  } catch (error: any) {
    console.error("[send-mfa-email] Unhandled error:", error?.message || error);
    return new Response(
      JSON.stringify({ error: error.message || "Internal Edge Function Error" }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
